version: '3'
services:
  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/app
    container_name: AppSymfony
    working_dir: /var/www/app
  nginx:
    image: nginx:latest
    ports:
      - "6888:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: NginxSymfony
  mysql:
    image: mysql:8
    command: mysqld --sql_mode="" --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "7888:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    container_name: DbSymfony